#!/usr/bin/python3
"""Build the launcher module (launchers.ini) from the [[launcher]] entries in
kbar.toml.

  launchers.py           write launchers.ini
  launchers.py --watch   keep watching kbar.toml; after each save, rebuild
                         launchers.ini and restart the bar if it changed
"""
import os
import re
import shlex
import shutil
import subprocess
import sys
import time
import tomllib

from common import CONFIG_DIR, THEME, TOML_PATH, clickable, fg, icon, notify, script

OUT = os.path.join(CONFIG_DIR, "launchers.ini")
HEADER = "; Generated by scripts/launchers.py from kbar.toml. Edit kbar.toml instead.\n"


def installed(entry):
    """Is the launcher's app present? Missing ones are left off the bar."""
    if entry.get("desktop"):
        name = entry["desktop"].removesuffix(".desktop") + ".desktop"
        dirs = [os.environ.get("XDG_DATA_HOME") or os.path.expanduser("~/.local/share")]
        dirs += (os.environ.get("XDG_DATA_DIRS") or "/usr/local/share:/usr/share").split(":")
        dirs += [os.path.expanduser("~/.local/share/flatpak/exports/share"), "/var/lib/flatpak/exports/share"]
        return any(os.path.exists(os.path.join(d, "applications", name)) for d in dirs)
    try:
        return bool(shutil.which(shlex.split(entry["command"])[0]))
    except (ValueError, IndexError):
        return False


def build():
    """Return (ini text, error message or None)."""
    try:
        with open(TOML_PATH, "rb") as f:
            entries = tomllib.load(f).get("launcher", [])
    except (OSError, tomllib.TOMLDecodeError) as e:
        warn = clickable(icon("󰀦", "coral"), left=script("launch-app", "--", "xdg-open", TOML_PATH))
        return f'{HEADER}[module/apps]\ntype = custom/text\nformat = "{warn}"\n', f"kbar.toml: {e}"
    cells, problems = [], []
    for i, e in enumerate(entries):
        name = e.get("name", f"launcher #{i}")
        if not e.get("icon") or not (e.get("desktop") or e.get("command")):
            problems.append(f"{name}: needs an icon and a desktop id or command")
            continue
        if not installed(e):
            continue
        c = e.get("color", "fg")
        if c not in THEME and not re.fullmatch(r"#[0-9a-fA-F]{6}", str(c)):
            problems.append(f"{name}: unknown colour {c!r}")
            c = "fg"
        cells.append(clickable(icon(e["icon"], c),
                               left=script("launch-app", str(i), "left"),
                               middle=script("launch-app", str(i), "middle") if e.get("middle") else None,
                               right=script("launch-app", str(i), "right") if e.get("right") else None))
    fmt = "%{O16}".join(cells) or fg("no launchers", "dim")
    return f'{HEADER}[module/apps]\ntype = custom/text\nformat = "{fmt}"\n', "; ".join(problems) or None


def write():
    text, error = build()
    try:
        with open(OUT) as f:
            changed = f.read() != text
    except OSError:
        changed = True
    if changed:
        with open(OUT + ".tmp", "w") as f:
            f.write(text)
        os.replace(OUT + ".tmp", OUT)
    if error:
        notify("kBar launchers", error, "dialog-warning")
    return changed


def watch():
    def mtime():
        try:
            return os.stat(TOML_PATH).st_mtime_ns
        except OSError:
            return 0
    seen = mtime()
    while True:
        time.sleep(1)
        now = mtime()
        if now == seen:
            continue
        seen = now
        time.sleep(0.3)                    # let editors finish writing
        if write():
            # run-bar exec'd into polybar, so our parent is the bar
            subprocess.run(["polybar-msg", "-p", str(os.getppid()), "cmd", "restart"], capture_output=True)
        else:                              # e.g. a new weather location
            for module in ("weather", "desktops"):
                subprocess.run([script("poke"), module, "refresh"])


if __name__ == "__main__":
    watch() if "--watch" in sys.argv else write()
